# Generated by Django 2.2.19 on 2021-09-02 02:38

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('processo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Processo')),
                ('outro', models.CharField(blank=True, max_length=140, verbose_name='Outro(s)')),
                ('destino_adm', models.CharField(blank=True, max_length=255, verbose_name='Destinatário')),
                ('oficiante', models.CharField(blank=True, max_length=255, verbose_name='Órgão/autoridade oficiante')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contato do oficiante')),
                ('fone', models.CharField(blank=True, max_length=15, verbose_name='Fone de contato do oficiante')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('arquivo', models.FileField(blank=True, upload_to='administrativo/inicial/%Y/%m/%d/', verbose_name='Documento')),
                ('assunto_adm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos_adm', to='core.AssuntoAdministrativo', verbose_name='Conteúdo principal')),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Processo',
                'verbose_name_plural': 'ADMINISTRATIVO - Processos',
            },
            bases=('core.processo',),
        ),
        migrations.CreateModel(
            name='AtoAdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em ')),
                ('tipo_ato', models.CharField(choices=[('1', 'OFÍCIO INTERNO'), ('2', 'OFÍCIO EXTERNO'), ('3', 'DESPACHO'), ('4', 'STATUS'), ('5', 'GRAVAÇÃO DE MÍDIA'), ('6', 'DOCUMENTO'), ('7', 'OFÍCIOS PARA EMPRESAS')], max_length=2, verbose_name='Tipo de Ato')),
                ('descricao', models.TextField(blank=True, verbose_name='Observação')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anular ato')),
                ('motivo_anulacao', models.TextField(blank=True, verbose_name='Motivo da anulação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atoadm_autor', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atoadm_modificador', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='adm.Administrativo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Administrativo - Ato',
                'verbose_name_plural': 'Administrativo - Atos',
            },
        ),
        migrations.CreateModel(
            name='ControlEmpresas',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Controle de Ofício',
                'verbose_name_plural': 'Controles de Ofícios',
            },
            bases=('adm.atoadm',),
        ),
        migrations.CreateModel(
            name='DespachoAdm',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('conteudo', models.TextField()),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Despacho',
                'verbose_name_plural': 'ADMINISTRATIVO - Despachos',
                'permissions': (('view_ato', 'Pode ver esse ato'),),
            },
            bases=('adm.atoadm', models.Model),
        ),
        migrations.CreateModel(
            name='DocumentosGeraisAdm',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('nome_doc', models.CharField(max_length=225, verbose_name='Nome do documento')),
                ('documento', models.FileField(upload_to='administrativo/documento_gerais/%Y/%m/%d/', validators=[core.validators.FileValidator(allowed_extensions=('doc', 'docx', 'odt', 'pdf', 'txt', 'xls', 'xlsx', 'rar', 'zip', 'jpeg', 'jpg', 'png'), max_size=25165824)], verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Documento geral',
                'verbose_name_plural': 'ADMINISTRATIVO - Documentos gerais',
                'permissions': (('view_ato', 'Pode ver esse ato'),),
            },
            bases=('adm.atoadm', models.Model),
        ),
        migrations.CreateModel(
            name='StatusAdm',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('local', models.CharField(blank=True, choices=[(None, 'Escolha o conteúdo principal'), ('ASSESSORIA DE IMPRENSA', '1. ASSESSORIA DE IMPRENSA'), ('ASSESSORIA DE PLANEJAMENTO', '2. ASSESSORIA DE PLANEJAMENTO'), ('ASSESSORIA JURÍDICA', '3. ASSESSORIA JURÍDICA'), ('ASSESSORIA MILITAR', '4. ASSESSORIA MILITAR'), ('CHEFIA DE GABINETE', '5. CHEFIA DE GABINETE'), ('CONSELHO SUPERIOR DE POLÍCIA CIVIL', '6. CONSELHO SUPERIOR DE POLÍCIA CIVIL'), (None, '7. DIRETORIA ADMINISTRATIVA FINANCEIRA'), ('ASSENTAMENTO FUNCIONAIS', '7.1. ASSENTAMENTO FUNCIONAIS'), ('COMISSÃO DE LICITAÇÃO', '7.2. COMISSÃO DE LICITAÇÃO'), ('COORDENAÇÃO DE COMPRAS', '7.3. COORDENAÇÃO DE COMPRAS'), ('COORDENAÇÃO DE MATERIAL', '7.4. COORDENAÇÃO DE MATERIAL'), ('COORDENAÇÃO DE SERVIÇOS GERAIS', '7.5. COORDENAÇÃO DE SERVIÇOS GERAIS'), ('COORDENAÇÃO DE SUPRIMENTO DE FUNDOS', '7.6. COORDENAÇÃO DE SUPRIMENTO DE FUNDOS'), ('COORDENAÇÃO DE TRANSPORTE', '7.6. COORDENAÇÃO DE TRANSPORTE'), ('FOLHA DE PAGAMENTO', '7.7. FOLHA DE PAGAMENTO'), ('GERÊNCIA DE ADMINISTRAÇÃO DE RECURSOS DE INFORMÁTICA', '7.8. GERÊNCIA DE ADMINISTRAÇÃO DE RECURSOS DE INFORMÁTICA'), ('GERÊNCIA DE PESSOAL', '7.9. GERÊNCIA DE PESSOAL'), ('GERÊNCIA FINANCEIRA', '7.10. GERÊNCIA FINANCEIRA'), ('NÚCLEO DE CONTROLE DE GESTÃO', '7.11. NÚCLEO DE CONTROLE DE GESTÃO'), ('PROTOCOLO GERAL', '7.12. PROTOCOLO GERAL'), ('SETOR DE ARQUIVO', '7.13. SETOR DE ARQUIVO'), ('SETOR DE EMPENHO', '7.14. SETOR DE EMPENHO'), ('SETOR DE ENGENHARIA', '7.15. SETOR DE ENGENHARIA'), ('SETOR DE INATIVOS', '7.16. SETOR DE INATIVOS'), ('DIRETORIA DE GESTÃO INTERNA', '8. DIRETORIA DE GESTÃO INTERNA'), ('Outro(s)', 'Outro(s)')], max_length=80, null=True, verbose_name='Localização')),
                ('outros', models.CharField(blank=True, max_length=100, verbose_name='Outro(s)')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação atual')),
                ('localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.LocalizacaoStatusAdm', verbose_name='Localizacao')),
            ],
            options={
                'verbose_name': 'Administrativo - Status',
                'ordering': ['id'],
            },
            bases=('adm.atoadm',),
        ),
        migrations.CreateModel(
            name='OficioInternoAdm',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('num_oficio', models.CharField(max_length=255, verbose_name='Gerar Número')),
                ('destino', models.CharField(max_length=140, verbose_name='Destinatário')),
                ('outros', models.CharField(blank=True, max_length=140, verbose_name='Outro(s)')),
                ('autoridade', models.CharField(max_length=80, verbose_name='Autoridade Policial que subscreve')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Recebido em')),
                ('confirmacao', models.BooleanField(blank=True, default=False, verbose_name='Ofício recebido')),
                ('nome_confirm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Funcionário/Pessoa que confirmou')),
                ('arquivo', models.FileField(blank=True, upload_to='administrativo/oficios_internos/%Y/%m/%d/', validators=[core.validators.FileValidator(allowed_extensions=('doc', 'docx', 'odt', 'pdf', 'txt', 'xls', 'xlsx', 'rar', 'zip', 'jpeg', 'jpg', 'png'), max_size=25165824)], verbose_name='Arquivo')),
                ('conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConteudoOficioInterno', verbose_name='Conteúdo principal')),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Ofício Interno',
                'verbose_name_plural': 'ADMINISTRATIVO - Ofícios Internos',
                'permissions': (('view_ato', 'Pode ver esse ato'),),
            },
            bases=('adm.atoadm', models.Model),
        ),
        migrations.CreateModel(
            name='OficioExternoAdm',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('num_oficio', models.CharField(max_length=140, verbose_name='Número do ofício')),
                ('origem', models.CharField(max_length=50, verbose_name='Autoridade/Órgão de origem')),
                ('outros', models.CharField(blank=True, max_length=140, verbose_name='Outros')),
                ('data_recebimento', models.DateField(verbose_name='Data de recebimento')),
                ('nome_recebimento', models.CharField(max_length=40, verbose_name='Funcionário que recebeu')),
                ('arquivo', models.FileField(blank=True, upload_to='administrativo/oficios_externos/%Y/%m/%d/', validators=[core.validators.FileValidator(allowed_extensions=('doc', 'docx', 'odt', 'pdf', 'txt', 'xls', 'xlsx', 'rar', 'zip', 'jpeg', 'jpg', 'png'), max_size=25165824)], verbose_name='Arquivo')),
                ('conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConteudoOficioExterno', verbose_name='Conteúdo principal')),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Ofício Externo',
                'verbose_name_plural': 'ADMINISTRATIVO - Ofícios Externos',
                'permissions': (('view_ato', 'Pode ver esse ato'),),
            },
            bases=('adm.atoadm', models.Model),
        ),
        migrations.CreateModel(
            name='OfEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em ')),
                ('empresa', models.CharField(choices=[(None, 'Selecione uma empresa'), ('1', 'Vivo'), ('2', 'Claro'), ('3', 'TIM'), ('4', 'Oi'), ('5', 'Algar'), ('6', 'Sercomtel'), ('7', 'Aeiou (Unicel)'), ('8', 'Nextel'), ('9', 'Transit'), ('10', 'Sky'), ('11', 'Telebras'), ('12', 'GVT'), ('13', 'Google'), ('14', 'Apple'), ('15', 'Microsoft'), ('16', 'NET'), ('17', 'Facebook'), ('18', 'Instagram'), ('19', 'Twitter'), ('20', 'Whatsapp'), ('21', 'Outros')], max_length=2, verbose_name='Destinatário')),
                ('outros', models.CharField(blank=True, max_length=80, verbose_name='Nome (Empresa)')),
                ('num_oficio', models.CharField(max_length=255, verbose_name='Número do Ofício')),
                ('autoridade', models.CharField(max_length=80, verbose_name='Autoridade Policial que Subscreve')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de envio do ofício')),
                ('confirmacao', models.BooleanField(blank=True, default=False, verbose_name='Ofício recebido')),
                ('nome_confirm', models.CharField(blank=True, max_length=20, verbose_name='Funcionário | Protocolo')),
                ('conteudo', models.TextField()),
                ('arquivo', models.FileField(blank=True, upload_to='processos/oficios_empresas/%Y/%m/%d/', validators=[core.validators.FileValidator(allowed_extensions=('doc', 'docx', 'odt', 'pdf', 'txt', 'xls', 'xlsx', 'rar', 'zip', 'jpeg', 'jpg', 'png'), max_size=25165824)], verbose_name='Arquivo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofempresas_autor', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofempresas_modificador', to=settings.AUTH_USER_MODEL)),
                ('controlempresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofempresas', to='adm.ControlEmpresas', verbose_name='Ofícios para empresas')),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Ofício para empresa',
                'verbose_name_plural': 'ADMINISTRATIVO - Ofícios para empresas',
                'permissions': (('view_ato', 'Pode ver esse ato'),),
            },
        ),
        migrations.CreateModel(
            name='MidiaAdm',
            fields=[
                ('atoadm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adm.AtoAdm')),
                ('destino', models.CharField(max_length=50, verbose_name='Destinatário')),
                ('solicitante', models.CharField(max_length=80, verbose_name='Órgão/Autoridade solicitante')),
                ('oforigem', models.CharField(blank=True, max_length=30, verbose_name='Ofício de origem')),
                ('tipo_gravacao', models.CharField(blank=True, choices=[('1', 'Integralidade dos áudios'), ('2', 'Áudios relevantes'), ('3', 'Áudios selecionados'), ('4', 'Gravação de Dados')], max_length=1, null=True, verbose_name='Tipo de gravação')),
                ('num_midia', models.CharField(max_length=255, verbose_name='Gerar Número')),
                ('docs', models.FileField(blank=True, null=True, upload_to='administrativo/midia/%Y/%m/%d/', verbose_name='Ofício de origem')),
                ('tipo_gravacao_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoGravacao', verbose_name='Tipo de gravação')),
            ],
            options={
                'verbose_name': 'ADMINISTRATIVO - Gravação de mídia',
                'verbose_name_plural': 'ADMINISTRATIVO - Gravações de mídia',
                'permissions': (('view_ato', 'Pode ver esse ato'),),
            },
            bases=('adm.atoadm', models.Model),
        ),
    ]
