# Generated by Django 2.2.19 on 2021-09-02 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
            ],
            options={
                'verbose_name': '[NORMALIZAÇÃO] Assunto (Administrativo)',
                'verbose_name_plural': '[NORMALIZAÇÃO] Assuntos (Administrativo)',
                'ordering': ['assunto'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoOficioExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=255, verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': '[NORMALIZAÇÃO] Conteúdo - Of. Recebido',
                'verbose_name_plural': '[NORMALIZAÇÃO] Conteúdos - Of. Recebidos',
                'ordering': ['conteudo'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoOficioInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=255, verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': '[NORMALIZAÇÃO] Conteúdo - Of. Expedido',
                'verbose_name_plural': '[NORMALIZAÇÃO] Conteúdos - Of. Expedidos',
                'ordering': ['conteudo'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoStatusAdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
            ],
            options={
                'verbose_name': '[NORMALIZAÇÃO] Status (Administrativo)',
                'verbose_name_plural': '[NORMALIZAÇÃO] Status (Administrativo)',
                'ordering': ['localizacao'],
            },
        ),
        migrations.CreateModel(
            name='MotivoVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em ')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': '[NORMALIZAÇÃO] Processo vinculado - Motivo',
                'verbose_name_plural': '[NORMALIZAÇÃO] Processos vinculados - Motivos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em ')),
                ('numero_processo', models.CharField(max_length=13, unique=True, verbose_name='Número do processo')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('arquivar', models.BooleanField(default=False, verbose_name='Arquivar processo')),
                ('data_arquivamento', models.DateField(blank=True, null=True, verbose_name='Arquivado em')),
                ('arquivador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_arquivador', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_autor', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_modificador', to=settings.AUTH_USER_MODEL)),
                ('orgao_processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='account.Orgao', verbose_name='Instituição a qual está vinculado')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['numero_processo'],
            },
        ),
        migrations.CreateModel(
            name='SequenciaDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em ')),
                ('sequencia', models.PositiveIntegerField(unique_for_date='criacao', verbose_name='Num de Sequência')),
            ],
            options={
                'verbose_name': 'Número de sequência de Processos',
                'verbose_name_plural': 'Números de sequência de Processos',
            },
        ),
        migrations.CreateModel(
            name='TipoGravacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': '[NORMALIZAÇÃO] Tipo de gravação de mídia',
                'verbose_name_plural': '[NORMALIZAÇÃO] Tipos de gravações de mídia',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='SequenciaDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em')),
                ('sequencia', models.PositiveIntegerField(verbose_name='Nº Sequencial')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('orgao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencias', to='account.Orgao', verbose_name='Órgão referencial')),
            ],
            options={
                'verbose_name': 'Número de sequência de documentos',
                'verbose_name_plural': 'Números de sequência de documentos',
            },
        ),
        migrations.CreateModel(
            name='VinculoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em ')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculoprocesso_autor', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculoprocesso_modificador', to=settings.AUTH_USER_MODEL)),
                ('motivo_vinculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.MotivoVinculo', verbose_name='Informe o motivo da vinculação')),
                ('processo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processoa_vinculos', to='core.Processo')),
                ('processo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processob_vinculos', to='core.Processo', verbose_name='Informe o número do processo vinculado')),
            ],
            options={
                'verbose_name': 'Processo vinculado',
                'verbose_name_plural': 'Processos vinculados',
                'ordering': ['criacao'],
                'unique_together': {('processo_a', 'processo_b')},
            },
        ),
    ]
